[package]
name = "breakout"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
rand = "0.6.3"
ordered-float = "1.0.1"

[dependencies.toybox-core]
version = "*"
path = "../core"
