[package]
name = "toybox-core"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
png = "*"
rand = "0.6.3"
rand_core = "0.3.0"
